@config.sql
@report/sql/definecfg.sql
@report/sql/generate_menu01.sql
@report/sql/generate_rman_menu01.sql
@report/list/dbinfo01.sql
@report/list/list_tablespacedb01.sql
@report/list/list_redolog01.sql
@report/list/list_checklist01.sql
@report/list/list_version01.sql
@report/list/list_corruptblock01.sql
@report/list/list_options01.sql
@report/list/list_encrypted_info01.sql
@report/list/list_param_modif01.sql
@report/list/list_param_nondefault01.sql
@report/list/list_param_hidden01.sql
@report/list/list_memory01.sql
@report/list/list_disabledtriggers01.sql
@report/list/list_invalidobjects01.sql
@report/list/list_size_db01.sql
@report/list/list_script_preexportdb01.sql
@report/list/list_rmanbkp01.sql
@report/list/list_rman_backupspfile01.sql
@report/list/list_rman_backupsize01.sql
@report/list/list_rman_backupset01.sql
@report/list/list_rman_backuppiece01.sql
@report/list/list_rman_backupjob01.sql
@report/list/list_archivehour01.sql
@report/list/list_archivemb01.sql
@report/list/list_dba_registry01.sql
@report/list/list_dba_usage01.sql
@report/list/list_options01.sql
@report/list/list_locked_stats01.sql
@report/list/list_nls_characters01.sql
@report/list/list_rebuildindex01.sql
@report/list/list_databasetriggers01.sql
@report/list/list_directory01.sql
@report/ddlscript/acl_ddl.sql
@report/ddlscript/audit_ddl.sql
@report/ddlscript/directory_ddl.sql
@report/ddlscript/dblink_ddl.sql
@report/ddlscript/getaud.sql
@report/ddlscript/job_ddl.sql
@report/ddlscript/job_ddl_19c.sql
-- @report/ddlscript/role_ddl.sql  -- can spend a lot of time
@report/ddlscript/tablespace_ddl.sql
@report/ddlscript/trigger_ddl.sql
@report/ddlscript/user_ddl.sql
@report/ddlscript/user_ddl_create.sql
@report/ddlscript/user_defined_type.sql
@report/bar/bar_archiveperday.sql
@report/bar/bar_tablespace.sql
@report/gauge/dbgauge_dashboard.sql
@report/gauge/dbgauge_opencursors.sql
@report/gauge/dbgauge_sessions.sql
@report/gauge/dbgauge_processes.sql
@report/gauge/dbgauge_opencursors.sql
@report/gauge/dbgauge_pga.sql
@report/gauge/dbgauge_transaction.sql
@report/gauge/dbgauge_usedspace.sql -- can spend a lot of time
@report/gauge/dbgauge_outstandingalerts.sql
@report/gauge/dbgauge_invalidobj.sql
@report/pie/dbpie_dashboard.sql
@report/pie/dbpie_shared_pool01.sql
@report/pie/dbpie_sga_pool01.sql
@report/pie/dbpie_segment_maxtable01.sql
@report/pie/dbpie_segment_maxsegment01.sql
@report/pie/dbpie_segment_maxindex01.sql
@report/pie/dbpie_segment_bigobjects01.sql
@report/pie/dbpie_resource_maxused01.sql
@report/pie/dbpie_resource_maxlimit01.sql
@report/pie/dbpie_resource_current01.sql
@report/pie/dbpie_object_types01.sql
@report/pie/dbpie_object_schema01.sql
@report/pie/dbpie_object_schema02.sql
@report/pie/dbpie_shared_poolcontents01.sql
@report/pie/dbpie_shared_poolcontents02.sql
@report/pie/dbpie_disabled_trigger01.sql
@report/pie/dbpie_rowlockwaits01.sql
@report/pie/dbpie_rowlockwaits02.sql
@report/pie/dbpie_physicalwaits02.sql
@report/pie/dbpie_physicalwaits01.sql
@report/pie/dbpie_bufferbusywaits03.sql
@report/pie/dbpie_bufferbusywaits02.sql
@report/pie/dbpie_result_cache01.sql
@report/pie/dbpie_bufferbusywaits01.sql
@report/pie/dbpie_disabled_trigger02.sql
@report/pie/dbpie_index_unusable01.sql
@report/pie/dbpie_index_unusable02.sql
@report/pie/dbpie_large_pool01.sql
@report/pie/dbpie_object_invalid01.sql
@report/pie/dbpie_object_invalid02.sql
@report/bar/bar_archiveperday.sql
@report/bar/bar_tablespace.sql
@report/script/script_stats_db01.sql
@report/expdp/expdp_script_create01.sql
@report/expdp/impdp_script_create01.sql
@report/expdp/dbinfo_expdp_list01.sql
@report/rman/report_rman_backup01.sql
@report/thirdparty/hcheck/report_hcheck.sql
@report/list/list_script_sysauxsize01.sql
@report/list/list_purge_recyclebin01.sql
@report/dataguard/dataguard_config.sql
--@report/sql/create_sendemail.sql
--@report/sql/creatermansendemail01.sql
@report/sql/zipoutputreport.sql
--host chmod +x &var_outputfolder/*.sh
--host &var_outputfolder/sendemail.sh
--host &var_outputfolder/sendrmanemail.sh
--host &var_outputfolder/zipoutputreport.sh
--host &var_outputfolder/zipoutputreport.sh
exit
