DEFINE vhtmlpage='role_ddl_'
DEFINE vtitlethispage='Roles DDL '
DEFINE viconthispage='shield-check.svg'
@report/sql/headerhtmlspool.sql

PRO <PRE>

PRO
PRO +------------------------------------------------------------------------------+
PRO |              ROLES                                                           |
PRO +------------------------------------------------------------------------------+
PRO

column ddl format a1000
variable v_role VARCHAR2(30);


select dbms_metadata.get_ddl('ROLE', r.role) AS ddl
from   dba_roles r
where  r.role   not IN ('ADM_PARALLEL_EXECUTE_TASK','APPLICATION_TRACE_VIEWER','AQ_ADMINISTRATOR_ROLE','AQ_USER_ROLE','AUDIT_ADMIN','AUDIT_VIEWER','AUTHENTICATEDUSER','CAPTURE_ADMIN','CDB_DBA','CONNECT',
'CSW_USR_ROLE','CTXAPP','DATAPATCH_ROLE','DATAPUMP_EXP_FULL_DATABASE','DATAPUMP_IMP_FULL_DATABASE','DBA','DBFS_ROLE','DBJAVASCRIPT','DBMS_MDX_INTERNAL',
'DV_ACCTMGR','DV_ADMIN','DV_AUDIT_CLEANUP','DV_DATAPUMP_NETWORK_LINK','DV_GOLDENGATE_ADMIN','DV_GOLDENGATE_REDO_ACCESS','DV_MONITOR','DV_OWNER','DV_PATCH_ADMIN',
'DV_POLICY_OWNER','DV_PUBLIC','DV_REALM_OWNER','DV_REALM_RESOURCE','DV_SECANALYST','DV_STREAMS_ADMIN','DV_XSTREAM_ADMIN','EJBCLIENT','EM_EXPRESS_ALL','EM_EXPRESS_BASIC','EXECUTE_CATALOG_ROLE',
'EXP_FULL_DATABASE','GATHER_SYSTEM_STATISTICS','GDS_CATALOG_SELECT','GGSYS_ROLE','GLOBAL_AQ_USER_ROLE','GSMADMIN_ROLE','GSMUSER_ROLE','GSM_POOLADMIN_ROLE','HS_ADMIN_EXECUTE_ROLE',
'HS_ADMIN_ROLE','HS_ADMIN_SELECT_ROLE','IMP_FULL_DATABASE','JAVADEBUGPRIV','JAVAIDPRIV','JAVASYSPRIV','JAVAUSERPRIV','JAVA_ADMIN','JAVA_DEPLOY','JMXSERVER','LBAC_DBA','LOGSTDBY_ADMINISTRATOR',
'OEM_ADVISOR','OEM_MONITOR','OLAP_DBA','OLAP_USER','OLAP_XS_ADMIN','OPTIMIZER_PROCESSING_RATE','ORDADMIN','PDB_DBA','PROVISIONER','RDFCTX_ADMIN','RECOVERY_CATALOG_OWNER','RECOVERY_CATALOG_OWNER_VPD',
'RECOVERY_CATALOG_USER','RESOURCE','SCHEDULER_ADMIN','SELECT_CATALOG_ROLE','SODA_APP','SPATIAL_CSW_ADMIN','SYSUMF_ROLE','WM_ADMIN_ROLE','XDBADMIN','XDB_SET_INVOKER','XDB_WEBSERVICES',
'XDB_WEBSERVICES_OVER_HTTP''DELETE_CATALOG_ROLE', 'MGMT_USER','XDB_WEBSERVICES_WITH_PUBLIC','XS_CACHE_ADMIN','XS_CONNECT','XS_NAMESPACE_ADMIN','XS_SESSION_ADMIN'
,'GSMROOTUSER_ROLE','BDSQL_ADMIN','BDSQL_USER','C##ADWC_ADMIN','C##ADWC_OPERATOR','C##ADWC_MONITOR'
,'DWROLE','CONSOLE_ADMIN','CONSOLE_OPERATOR','CONSOLE_MONITOR','CONSOLE_DEVELOPER','DATAPUMP_CLOUD_EXP','DATAPUMP_CLOUD_IMP','OML_DEVELOPER','APEX_ADMINISTRATOR_READ_ROLE'
,'APEX_ADMINISTRATOR_ROLE','APEX_GRANTS_FOR_NEW_USERS_ROLE','ORDS_ADMINISTRATOR_ROLE','OML_SYS_ADMIN'
,'AVTUNE_PKG_ROLE','ADB_MONITOR','ORDS_RUNTIME_ROLE','ADP_SERVICE$IMPL'
,'LINEAGE_AUTHOR','LINEAGE_ADMIN','LINEAGE$IMPL','CLOUD_INGEST$IMPL','CLOUD_INGEST_USER','CLOUD_INGEST_ADMIN','INSIGHT_AUTHOR','INSIGHT_ADMIN'
,'INSIGHT$IMPL','EXTAPP','ADPUSER','INGEST_REC_INTERNAL$IMPL','GRAPH_DEVELOPER','PYQADMIN','ODI_LINEAGE_USER','ODI_LINEAGE_ADMIN')
/
select dbms_metadata.get_granted_ddl('ROLE_GRANT', rp.grantee) AS ddl
from   dba_role_privs rp
where  rp.GRANTED_ROLE   not IN ('ADM_PARALLEL_EXECUTE_TASK','APPLICATION_TRACE_VIEWER','AQ_ADMINISTRATOR_ROLE','AQ_USER_ROLE','AUDIT_ADMIN','AUDIT_VIEWER','AUTHENTICATEDUSER','CAPTURE_ADMIN','CDB_DBA','CONNECT',
'CSW_USR_ROLE','CTXAPP','DATAPATCH_ROLE','DATAPUMP_EXP_FULL_DATABASE','DATAPUMP_IMP_FULL_DATABASE','DBA','DBFS_ROLE','DBJAVASCRIPT','DBMS_MDX_INTERNAL',
'DV_ACCTMGR','DV_ADMIN','DV_AUDIT_CLEANUP','DV_DATAPUMP_NETWORK_LINK','DV_GOLDENGATE_ADMIN','DV_GOLDENGATE_REDO_ACCESS','DV_MONITOR','DV_OWNER','DV_PATCH_ADMIN',
'DV_POLICY_OWNER','DV_PUBLIC','DV_REALM_OWNER','DV_REALM_RESOURCE','DV_SECANALYST','DV_STREAMS_ADMIN','DV_XSTREAM_ADMIN','EJBCLIENT','EM_EXPRESS_ALL','EM_EXPRESS_BASIC','EXECUTE_CATALOG_ROLE',
'EXP_FULL_DATABASE','GATHER_SYSTEM_STATISTICS','GDS_CATALOG_SELECT','GGSYS_ROLE','GLOBAL_AQ_USER_ROLE','GSMADMIN_ROLE','GSMUSER_ROLE','GSM_POOLADMIN_ROLE','HS_ADMIN_EXECUTE_ROLE',
'HS_ADMIN_ROLE','HS_ADMIN_SELECT_ROLE','IMP_FULL_DATABASE','JAVADEBUGPRIV','JAVAIDPRIV','JAVASYSPRIV','JAVAUSERPRIV','JAVA_ADMIN','JAVA_DEPLOY','JMXSERVER','LBAC_DBA','LOGSTDBY_ADMINISTRATOR',
'OEM_ADVISOR','OEM_MONITOR','OLAP_DBA','OLAP_USER','OLAP_XS_ADMIN','OPTIMIZER_PROCESSING_RATE','ORDADMIN','PDB_DBA','PROVISIONER','RDFCTX_ADMIN','RECOVERY_CATALOG_OWNER','RECOVERY_CATALOG_OWNER_VPD',
'RECOVERY_CATALOG_USER','RESOURCE','SCHEDULER_ADMIN','SELECT_CATALOG_ROLE','SODA_APP','SPATIAL_CSW_ADMIN','SYSUMF_ROLE','WM_ADMIN_ROLE','XDBADMIN','XDB_SET_INVOKER','XDB_WEBSERVICES',
'XDB_WEBSERVICES_OVER_HTTP''DELETE_CATALOG_ROLE', 'MGMT_USER','XDB_WEBSERVICES_WITH_PUBLIC','XS_CACHE_ADMIN','XS_CONNECT','XS_NAMESPACE_ADMIN','XS_SESSION_ADMIN'
,'GSMROOTUSER_ROLE','BDSQL_ADMIN','BDSQL_USER','C##ADWC_ADMIN','C##ADWC_OPERATOR','C##ADWC_MONITOR'
,'DWROLE','CONSOLE_ADMIN','CONSOLE_OPERATOR','CONSOLE_MONITOR','CONSOLE_DEVELOPER','DATAPUMP_CLOUD_EXP','DATAPUMP_CLOUD_IMP','OML_DEVELOPER','APEX_ADMINISTRATOR_READ_ROLE'
,'APEX_ADMINISTRATOR_ROLE','APEX_GRANTS_FOR_NEW_USERS_ROLE','ORDS_ADMINISTRATOR_ROLE','OML_SYS_ADMIN'
,'AVTUNE_PKG_ROLE','ADB_MONITOR','ORDS_RUNTIME_ROLE','ADP_SERVICE$IMPL'
,'LINEAGE_AUTHOR','LINEAGE_ADMIN','LINEAGE$IMPL','CLOUD_INGEST$IMPL','CLOUD_INGEST_USER','CLOUD_INGEST_ADMIN','INSIGHT_AUTHOR','INSIGHT_ADMIN'
,'INSIGHT$IMPL','EXTAPP','ADPUSER','INGEST_REC_INTERNAL$IMPL','GRAPH_DEVELOPER','PYQADMIN','ODI_LINEAGE_USER','ODI_LINEAGE_ADMIN')

/
select dbms_metadata.get_granted_ddl('SYSTEM_GRANT', sp.grantee) AS ddl
from   dba_sys_privs sp
/
select dbms_metadata.get_granted_ddl('OBJECT_GRANT', tp.grantee) AS ddl
from   dba_tab_privs tp
/


@report/sql/footerhtml01
