PRO
PRO
PRO </PRE>
PRO <font class="f">rock script (c) 2021. Version v1.0 (2021-03-01). Timestamp: &varTIMESTAMP </font>
PRO

 
SPO OFF;
SET HEA ON LIN 80 NEWP 1 PAGES 14 FEED ON ECHO OFF VER ON LONG 80 LONGC 80 WRA ON TRIMS OFF TRIM OFF TI OFF TIMI OFF ARRAY 15 NUM 10 NUMF "" SQLBL OFF BLO ON RECSEP WR;
